/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class space_gameressence_atiburcio_tyler_Useful */

#ifndef _Included_space_gameressence_atiburcio_tyler_Useful
#define _Included_space_gameressence_atiburcio_tyler_Useful
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     space_gameressence_atiburcio_tyler_Useful
 * Method:    method
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_space_gameressence_atiburcio_tyler_Useful_method
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
